<?php

namespace AcMarche\Volontariat\Repository;

use AcMarche\Volontariat\Entity\Security\Group;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * GroupRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class GroupRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Group::class);
    }

    public function insert(Group $group): void
    {
        $this->_em->persist($group);
        $this->save();
    }

    public function save(): void
    {
        $this->_em->flush();
    }

    public function remove(Group $group): void
    {
        $this->_em->remove($group);
        $this->save();
    }
}
