<?php

namespace AcMarche\Volontariat\Repository;

use AcMarche\Volontariat\Entity\Temoignage;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 *
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TemoignageRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Temoignage::class);
    }


    public function insert(Temoignage $temoignage): void
    {
        $this->_em->persist($temoignage);
        $this->flush();
    }

    public function flush(): void
    {
        $this->_em->flush();
    }

    public function remove(Temoignage $temoignage): void
    {
        $this->_em->remove($temoignage);
        $this->flush();
    }
}
