<?php

namespace AcMarche\Volontariat\Repository;

use AcMarche\Volontariat\Entity\Vehicule;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * VehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculeRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Vehicule::class);
    }


    public function insert(Vehicule $vehicule)
    {
        $this->_em->persist($vehicule);
        $this->save();
    }

    public function save()
    {
        $this->_em->flush();
    }

    public function remove(Vehicule $vehicule)
    {
        $this->_em->remove($vehicule);
        $this->save();
    }

    public function findAll()
    {
        return $this->findBy(array(), array('nom' => 'ASC'));
    }

    /**
     * @return Vehicule[]
     */
    public function getForSearch()
    {
        $qb = $this->createQueryBuilder('vehicule');

        $qb->orderBy('vehicule.nom');
        $query = $qb->getQuery();

        $results = $query->getResult();
        $types = array();

        foreach ($results as $type) {
            $types[$type->getNom()] = $type->getId();
        }

        return $types;
    }
}
