<?php

namespace AcMarche\Volontariat\Repository;

use AcMarche\Volontariat\Entity\Vehicule;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * VehiculeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @extends ServiceEntityRepository<Vehicule>
 */
class VehiculeRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $managerRegistry)
    {
        parent::__construct($managerRegistry, Vehicule::class);
    }


    public function insert(Vehicule $vehicule): void
    {
        $this->_em->persist($vehicule);
        $this->flush();
    }

    public function flush(): void
    {
        $this->_em->flush();
    }

    public function remove(Vehicule $vehicule): void
    {
        $this->_em->remove($vehicule);
        $this->flush();
    }

    public function findAll(): array
    {
        return $this->findBy(array(), array('nom' => 'ASC'));
    }

    /**
     * @return Vehicule[]
     */
    public function getForSearch(): array
    {
        $queryBuilder = $this->createQueryBuilder('vehicule');

        $queryBuilder->orderBy('vehicule.nom');

        $query = $queryBuilder->getQuery();

        $results = $query->getResult();
        $types = array();

        foreach ($results as $result) {
            $types[$result->getNom()] = $result->getId();
        }

        return $types;
    }
}
