<?php

namespace AcMarche\Volontariat\Event;

enum VolontariatEnum: string
{
    case ACTIVITE_NEW = 'ACTIVITE_NEW';
    case ACTIVITE_EDIT = 'ACTIVITE_EDIT';
    case ACTIVITE_DELETE = 'ACTIVITE_DELETE';
    case ACTIVITE_VALIDER_REQUEST = 'ACTIVITE_VALIDER_REQUEST';
    case ACTIVITE_VALIDER_FINISH = 'ACTIVITE_VALIDER_FINISH';
    case ASSOCIATION_NEW = 'ASSOCIATION_NEW';
    case ASSOCIATION_VALIDER_REQUEST = 'ASSOCIATION_VALIDER_REQUEST';
    case ASSOCIATION_VALIDER_FINISH = 'ASSOCIATION_VALIDER_FINISH';
    case VOLONTAIRE_NEW = 'VOLONTAIRE_NEW';
}
